version: "3"

services:
  php:
    image: wodby/drupal:$DRUPAL_TAG
    environment:
      PHP_FPM_CLEAR_ENV: "no"
    volumes:
      - ./codebase:/var/www/html

  nginx:
    environment:
      NGINX_SERVER_ROOT: /var/www/html/web
    volumes:
      - ./codebase:/var/www/html

volumes:
  codebase:
